// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Packet {

  /// <summary>Holder for reflection information generated from Packet.proto</summary>
  public static partial class PacketReflection {

    #region Descriptor
    /// <summary>File descriptor for Packet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxQYWNrZXQucHJvdG8SBnBhY2tldBoPVHJhbnNmb3JtLnByb3RvGgpSb29t",
            "LnByb3RvKuYBCghQYWNrZXRJRBIZChVTX0NPTk5FQ1RFRF9UT19TRVJWRVIQ",
            "ABITCg9DX1JPT01fTElTVF9SRVEQARITCg9TX1JPT01fTElTVF9SRVMQAhIR",
            "Cg1DX0NSRUFURV9ST09NEAMSFAoQQ19FTlRFUl9ST09NX1JFURAEEhQKEFNf",
            "RU5URVJfUk9PTV9SRVMQBRIQCgxDX0xFQVZFX1JPT00QBhIYChRTX1VOSUNB",
            "U1RfTEVBVkVfUk9PTRAHEhAKDENfU1RBUlRfR0FNRRAIEhgKFFNfVU5JQ0FT",
            "VF9TVEFSVF9HQU1FEAlCGaoCFkdvb2dsZS5Qcm90b2J1Zi5QYWNrZXRiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Packet.TransformReflection.Descriptor, global::Packet.RoomReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Packet.PacketID), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PacketID {
    [pbr::OriginalName("S_CONNECTED_TO_SERVER")] SConnectedToServer = 0,
    [pbr::OriginalName("C_ROOM_LIST_REQ")] CRoomListReq = 1,
    [pbr::OriginalName("S_ROOM_LIST_RES")] SRoomListRes = 2,
    [pbr::OriginalName("C_CREATE_ROOM")] CCreateRoom = 3,
    [pbr::OriginalName("C_ENTER_ROOM_REQ")] CEnterRoomReq = 4,
    [pbr::OriginalName("S_ENTER_ROOM_RES")] SEnterRoomRes = 5,
    [pbr::OriginalName("C_LEAVE_ROOM")] CLeaveRoom = 6,
    [pbr::OriginalName("S_UNICAST_LEAVE_ROOM")] SUnicastLeaveRoom = 7,
    [pbr::OriginalName("C_START_GAME")] CStartGame = 8,
    [pbr::OriginalName("S_UNICAST_START_GAME")] SUnicastStartGame = 9,
  }

  #endregion

}

#endregion Designer generated code
