// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MagicKnights.Api.Packet {

  /// <summary>Holder for reflection information generated from Packet.proto</summary>
  public static partial class PacketReflection {

    #region Descriptor
    /// <summary>File descriptor for Packet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxQYWNrZXQucHJvdG8SBnBhY2tldCqDAgoJRVBhY2tldElEEhkKFVNfQ09O",
            "TkVDVEVEX1RPX1NFUlZFUhAAEhMKD0NfUk9PTV9MSVNUX1JFURABEhMKD1Nf",
            "Uk9PTV9MSVNUX1JFUxACEhEKDUNfQ1JFQVRFX1JPT00QAxIUChBDX0VOVEVS",
            "X1JPT01fUkVREAQSFAoQU19FTlRFUl9ST09NX1JFUxAFEhAKDENfTEVBVkVf",
            "Uk9PTRAGEhgKFFNfVU5JQ0FTVF9MRUFWRV9ST09NEAcSFAoQQ19TVEFSVF9H",
            "QU1FX1JFURAIEhgKFFNfVU5JQ0FTVF9TVEFSVF9HQU1FEAkSCgoGQ19NT1ZF",
            "EAoSCgoGU19NT1ZFEAtCGqoCF01hZ2ljS25pZ2h0cy5BcGkuUGFja2V0YgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MagicKnights.Api.Packet.EPacketID), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EPacketID {
    [pbr::OriginalName("S_CONNECTED_TO_SERVER")] SConnectedToServer = 0,
    [pbr::OriginalName("C_ROOM_LIST_REQ")] CRoomListReq = 1,
    [pbr::OriginalName("S_ROOM_LIST_RES")] SRoomListRes = 2,
    [pbr::OriginalName("C_CREATE_ROOM")] CCreateRoom = 3,
    [pbr::OriginalName("C_ENTER_ROOM_REQ")] CEnterRoomReq = 4,
    [pbr::OriginalName("S_ENTER_ROOM_RES")] SEnterRoomRes = 5,
    [pbr::OriginalName("C_LEAVE_ROOM")] CLeaveRoom = 6,
    [pbr::OriginalName("S_UNICAST_LEAVE_ROOM")] SUnicastLeaveRoom = 7,
    [pbr::OriginalName("C_START_GAME_REQ")] CStartGameReq = 8,
    [pbr::OriginalName("S_UNICAST_START_GAME")] SUnicastStartGame = 9,
    [pbr::OriginalName("C_MOVE")] CMove = 10,
    [pbr::OriginalName("S_MOVE")] SMove = 11,
  }

  #endregion

}

#endregion Designer generated code
