// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MagicKnights.Api.Packet {

  /// <summary>Holder for reflection information generated from Packet.proto</summary>
  public static partial class PacketReflection {

    #region Descriptor
    /// <summary>File descriptor for Packet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxQYWNrZXQucHJvdG8SBnBhY2tldCqKAgoJRVBhY2tldElEEhkKFVNfQ09O",
            "TkVDVEVEX1RPX1NFUlZFUhAAEhMKD0NfUk9PTV9MSVNUX1JFURABEg8KC1Nf",
            "Uk9PTV9MSVNUEAISEQoNQ19DUkVBVEVfUk9PTRADEhQKEENfRU5URVJfUk9P",
            "TV9SRVEQBBIUChBTX0VOVEVSX1JPT01fUkVTEAUSEAoMQ19MRUFWRV9ST09N",
            "EAYSGAoUU19VTklDQVNUX0xFQVZFX1JPT00QBxIUChBDX1NUQVJUX0dBTUVf",
            "UkVREAgSFwoTU19OT1RJRllfU1RBUlRfR0FNRRAJEhAKDENfTU9WRV9JTlBV",
            "VBAKEhAKDFNfTU9WRV9JTlBVVBALQhqqAhdNYWdpY0tuaWdodHMuQXBpLlBh",
            "Y2tldGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MagicKnights.Api.Packet.EPacketID), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EPacketID {
    [pbr::OriginalName("S_CONNECTED_TO_SERVER")] SConnectedToServer = 0,
    [pbr::OriginalName("C_ROOM_LIST_REQ")] CRoomListReq = 1,
    [pbr::OriginalName("S_ROOM_LIST")] SRoomList = 2,
    [pbr::OriginalName("C_CREATE_ROOM")] CCreateRoom = 3,
    [pbr::OriginalName("C_ENTER_ROOM_REQ")] CEnterRoomReq = 4,
    [pbr::OriginalName("S_ENTER_ROOM_RES")] SEnterRoomRes = 5,
    [pbr::OriginalName("C_LEAVE_ROOM")] CLeaveRoom = 6,
    [pbr::OriginalName("S_UNICAST_LEAVE_ROOM")] SUnicastLeaveRoom = 7,
    [pbr::OriginalName("C_START_GAME_REQ")] CStartGameReq = 8,
    [pbr::OriginalName("S_NOTIFY_START_GAME")] SNotifyStartGame = 9,
    [pbr::OriginalName("C_MOVE_INPUT")] CMoveInput = 10,
    [pbr::OriginalName("S_MOVE_INPUT")] SMoveInput = 11,
  }

  #endregion

}

#endregion Designer generated code
